### ISSUE TITLE
Windows: UAC blocks Symlinks

### ISSUE THREAD

**Issue by T-256** [mitsuhiko/rye#131]
### Steps to Reproduce

tesing https://github.com/mitsuhiko/rye/pull/125

1. `mkdir test && cd test`
2. `rye init`
3. `rye sync`

### Expected Result

No Error

### Actual Result

```
Bootstrapping rye internals
Downloading cpython@3.10.9
Checking hash
success: Downloaded cpython@3.10.9
Upgrading pip
Installing internal dependencies
Error: could not sync because bootstrap failed

Caused by:
    0: tried to symlink python shim
    1: A required privilege is not held by the client. (os error 1314)
```

### Version Info

```
rye 0.1.0
commit: unknown (07a1036ed 2023-05-10)
platform: windows 22621.1702 (x86_64)
self-python: cpython@3.10
```

### Stacktrace

```
detected outdated rye internals. Refreshing
Bootstrapping rye internals
Upgrading pip
Installing internal dependencies
Error: could not sync because bootstrap failed

Caused by:
    0: tried to symlink python shim
    1: A required privilege is not held by the client. (os error 1314)

Stack backtrace:
   0: backtrace::backtrace::trace
   1: anyhow::backtrace::capture::Backtrace::capture
   2: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
   3: rye::bootstrap::ensure_self_venv
   4: rye::sync::sync
   5: rye::cli::sync::execute
   6: rye::cli::execute
   7: rye::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src/rt.rs:148:20
  11: main
  12: __tmainCRTStartup
             at C:\M\mingw-w64-crt-git\src\crt-x86_64-w64-mingw32\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:321:15
  13: mainCRTStartup
             at C:\M\mingw-w64-crt-git\src\crt-x86_64-w64-mingw32\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:202:9
  14: <unknown>
  15: <unknown>
```

**Comment by mitsuhiko** [comment]
Which Windows version is this?

**Comment by T-256** [comment]
platform: windows 22621.1702 (x86_64)

**Comment by mitsuhiko** [comment]
Sounds like administrator accounts are prevented from setting symlinks unless they pass UAC? I thought this was  Vista thing though. https://learn.microsoft.com/en-us/answers/questions/774304/symbolic-link-polic-group-isnt-working

**Comment by mitsuhiko** [comment]
So what seems to be happening is that windows when using the `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag (which Rust uses) permits non admin accounts to create symlinks. However that requires developer mode to be turned on (https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka)

**Comment by T-256** [comment]
it seems junction doesn't need this privilege: https://stackoverflow.com/a/48586946

**Comment by mitsuhiko** [comment]
@T-256 yeah, I will have a look at if I can make it work with junctions. In the past one of the issues was that tools were liberally deleting into junctions. But supposedly a lot of this was fixed with Windows 10.

**Comment by mitsuhiko** [comment]
I think this is sufficiently solved now.

**Comment by T-256** [comment]
not fixed on latest `rye v0.1.0 (https://github.com/mitsuhiko/rye#09da2809)`
```
E:\ryetest>rye toolchain register C:\python37x86\python.exe --name=test
Error: could not symlink interpreter

Caused by:
    A required privilege is not held by the client. (os error 1314)

E:\ryetest>
```

**Comment by T-256** [comment]
hard link has bi issues:
```py3
E:\ryetest>python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.link('C:\python37x86\python.exe', r'python.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\python37x86\\python.exe' -> 'python.exe'
```

**Comment by T-256** [comment]
why not just use files with absolute path for registered interpreters?

**Comment by mitsuhiko** [comment]
@T-256 it's fixed in the general case with the exception of the toolchain registry.

https://github.com/mitsuhiko/rye/blob/09da2809b6fe6f5d46e7b6305d11965fd8a85a4b/rye/src/cli/toolchain.rs#L120-L124

I will open an issue for this.
